// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/Kaiofprates/avocato-db"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/append": {
            "post": {
                "description": "Creates a new immutable block with the provided payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ledger"
                ],
                "summary": "Append data to the ledger",
                "parameters": [
                    {
                        "description": "Data payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AppendRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.AppendResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/block/{id}": {
            "get": {
                "description": "Retrieves a specific block from the ledger. UUID or Hash are recommended for security.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ledger"
                ],
                "summary": "Get block by UUID, hash or index",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Block UUID, hash or index",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.BlockResponse"
                        }
                    },
                    "404": {
                        "description": "Block not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/integrity": {
            "get": {
                "description": "Returns the current state of the ledger and the MMR root",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrity"
                ],
                "summary": "Get ledger integrity status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.IntegrityResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.AppendRequest": {
            "type": "object",
            "properties": {
                "payload": {}
            }
        },
        "handlers.AppendResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "hash": {
                            "type": "string"
                        },
                        "index": {
                            "type": "integer"
                        },
                        "prev_hash": {
                            "type": "string"
                        },
                        "timestamp": {
                            "type": "integer"
                        },
                        "uuid": {
                            "type": "string"
                        }
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handlers.BlockResponse": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "payload": {},
                "prev_hash": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "handlers.IntegrityResponse": {
            "type": "object",
            "properties": {
                "mmr_root": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "total_blocks": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.2.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "avocato-db API",
	Description:      "Immutable, append-only, hash-protected database engine.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
